CREATE TABLE "SQL_Project"."CovidVaccinations"
(iso_code varchar,
 continent varchar,
 location varchar,
 entry_date date,
 new_tests varchar,
 total_tests_per_thousand varchar,
 new_tests_per_thousand varchar,
 new_tests_smoothed varchar,
 new_tests_smoothed_per_thousand varchar,
 positive_rate varchar,
 tests_per_case varchar,
 tests_units varchar,
 total_vaccinations varchar,
 people_vaccinated varchar,
 people_fully_vaccinated varchar,
 total_boosters varchar,
 new_vaccinations varchar,
 new_vaccinations_smoothed varchar,
 total_vaccinations_per_hundred varchar,
 people_vaccinated_per_hundred varchar,
 people_fully_vaccinated_per_hundred varchar,
 total_boosters_per_hundred varchar,
 new_vaccinations_smoothed_per_million varchar,
 new_people_vaccinated_smoothed varchar,
 new_people_vaccinated_smoothed_per_hundred varchar,
 stringency_index varchar,
 population_density varchar,
 median_age varchar,
 aged_65_older varchar,
 aged_70_older varchar,
 gdp_per_capita varchar,
 extreme_poverty varchar,
 cardiovasc_death_rate varchar,
 diabetes_prevalence varchar,
 female_smokers varchar,
 male_smokers varchar,
 handwashing_facilities varchar,
 hospital_beds_per_thousand varchar,
 life_expectancy varchar,
 human_development_index varchar,
 excess_mortality_cumulative_absolute varchar,
 excess_mortality_cumulative varchar,
 excess_mortality varchar,
 excess_mortality_cumulative_per_million varchar
)
;

ALTER TABLE IF EXISTS "SQL_Project"."CovidVaccinations"
    OWNER to postgres;